API 4.0.0
aternosorg/mclogs-bukkit pull request #10
Opened 2023-06-15 16:14 UTC by TheRealRyGuy

- Updates gradle wrapper to 8.1.1, as well as gradle plugins
- Updates workflow versions, uses gradle validation 
- Uses proper submodule setup 
- Uses java 11 
- Uses API version 4.0.0

Note: Releasing will have to be altered with the shadow update, likely just to fix naming conventions. This will also require updating the release workflow

2023-06-15 16:17 UTC, JulianVennen requested changes

2023-06-15 16:17 UTC, JulianVennen commented on build.gradle
> +    implementation project(path: ":mclogs-java", configuration: 'default')
Please continue using maven central here, 4.0.1 is already synced

2023-06-15 18:13 UTC, JulianVennen requested changes

2023-06-15 18:13 UTC, JulianVennen commented on build.gradle
> +    id "maven-publish"
not sure why you added maven-publish

2023-06-15 18:13 UTC, JulianVennen commented
I'll merge this tomorrow, I can also do these changes myself then. Once again, thanks for your contributions.

2023-06-16 03:16 UTC, TheRealRyGuy commented
all done, and pulled some other things you did today from other repos :+1: didn't realize I missed so much, apologies

2023-06-16 09:38 UTC, JulianVennen requested changes

2023-06-16 09:38 UTC, JulianVennen commented on .github/workflows/build.yml
> +      run: git submodule init && git submodule update
this is no longer required

2023-06-16 09:38 UTC, JulianVennen commented on settings.gradle
> +project(':mclogs-java').projectDir = new File('./mclogs-java/')
this is also not required anymore

2023-06-16 16:25 UTC, merged